/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.Service"
      "url": string
    }
    "Beat": {
      "type": "sst.aws.Service"
    }
    "FitbitClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FitbitClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Frontend": {
      "type": "sst.aws.Service"
      "url": string
    }
    "GarminClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GarminClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MedplumClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MedplumClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MedplumWebhookUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Worker": {
      "type": "sst.aws.Service"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}