/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WidgetConnectRouteImport } from './routes/widget.connect'
import { Route as SlLoginRouteImport } from './routes/sl/login'
import { Route as SlForgotPasswordRouteImport } from './routes/sl/forgot-password'
import { Route as SlSlAuthenticatedRouteImport } from './routes/sl/_sl-authenticated'
import { Route as AuthenticatedWebhooksRouteImport } from './routes/_authenticated/webhooks'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedWebhooksIndexRouteImport } from './routes/_authenticated/webhooks/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as UsersUserIdPairRouteImport } from './routes/users/$userId/pair'
import { Route as SlSlAuthenticatedDashboardRouteImport } from './routes/sl/_sl-authenticated/dashboard'
import { Route as AuthenticatedWebhooksEndpointIdRouteImport } from './routes/_authenticated/webhooks/$endpointId'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users/$userId'
import { Route as UsersUserIdPairIndexRouteImport } from './routes/users/$userId/pair.index'
import { Route as SlSlAuthenticatedPatientsIndexRouteImport } from './routes/sl/_sl-authenticated/patients/index'
import { Route as SlSlAuthenticatedInstructionTemplatesIndexRouteImport } from './routes/sl/_sl-authenticated/instruction-templates/index'
import { Route as SlSlAuthenticatedCliniciansIndexRouteImport } from './routes/sl/_sl-authenticated/clinicians/index'
import { Route as SlSlAuthenticatedAlertsIndexRouteImport } from './routes/sl/_sl-authenticated/alerts/index'
import { Route as UsersUserIdPairSuccessRouteImport } from './routes/users/$userId/pair.success'
import { Route as UsersUserIdPairErrorRouteImport } from './routes/users/$userId/pair.error'
import { Route as SlSetPasswordInviteIdSecretRouteImport } from './routes/sl/set-password/$inviteId/$secret'
import { Route as SlSlAuthenticatedPatientsPatientIdRouteImport } from './routes/sl/_sl-authenticated/patients/$patientId'
import { Route as SlSlAuthenticatedInstructionTemplatesTemplateIdRouteImport } from './routes/sl/_sl-authenticated/instruction-templates/$templateId'
import { Route as SlSlAuthenticatedCliniciansClinicianIdRouteImport } from './routes/sl/_sl-authenticated/clinicians/$clinicianId'
import { Route as SlSlAuthenticatedAlertsAlertIdRouteImport } from './routes/sl/_sl-authenticated/alerts/$alertId'
import { Route as SlSlAuthenticatedPatientsPatientIdIndexRouteImport } from './routes/sl/_sl-authenticated/patients/$patientId/index'
import { Route as SlSlAuthenticatedInstructionTemplatesQuestionnairesQuestionnaireIdRouteImport } from './routes/sl/_sl-authenticated/instruction-templates/questionnaires.$questionnaireId'
import { Route as SlSlAuthenticatedPatientsPatientIdPlansPlanIdEditRouteImport } from './routes/sl/_sl-authenticated/patients/$patientId/plans.$planId.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetConnectRoute = WidgetConnectRouteImport.update({
  id: '/widget/connect',
  path: '/widget/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const SlLoginRoute = SlLoginRouteImport.update({
  id: '/sl/login',
  path: '/sl/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SlForgotPasswordRoute = SlForgotPasswordRouteImport.update({
  id: '/sl/forgot-password',
  path: '/sl/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SlSlAuthenticatedRoute = SlSlAuthenticatedRouteImport.update({
  id: '/sl/_sl-authenticated',
  path: '/sl',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWebhooksRoute = AuthenticatedWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWebhooksIndexRoute =
  AuthenticatedWebhooksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWebhooksRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)
const UsersUserIdPairRoute = UsersUserIdPairRouteImport.update({
  id: '/users/$userId/pair',
  path: '/users/$userId/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const SlSlAuthenticatedDashboardRoute =
  SlSlAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => SlSlAuthenticatedRoute,
  } as any)
const AuthenticatedWebhooksEndpointIdRoute =
  AuthenticatedWebhooksEndpointIdRouteImport.update({
    id: '/$endpointId',
    path: '/$endpointId',
    getParentRoute: () => AuthenticatedWebhooksRoute,
  } as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedUsersRoute,
  } as any)
const UsersUserIdPairIndexRoute = UsersUserIdPairIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersUserIdPairRoute,
} as any)
const SlSlAuthenticatedPatientsIndexRoute =
  SlSlAuthenticatedPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => SlSlAuthenticatedRoute,
  } as any)
const SlSlAuthenticatedInstructionTemplatesIndexRoute =
  SlSlAuthenticatedInstructionTemplatesIndexRouteImport.update({
    id: '/instruction-templates/',
    path: '/instruction-templates/',
    getParentRoute: () => SlSlAuthenticatedRoute,
  } as any)
const SlSlAuthenticatedCliniciansIndexRoute =
  SlSlAuthenticatedCliniciansIndexRouteImport.update({
    id: '/clinicians/',
    path: '/clinicians/',
    getParentRoute: () => SlSlAuthenticatedRoute,
  } as any)
const SlSlAuthenticatedAlertsIndexRoute =
  SlSlAuthenticatedAlertsIndexRouteImport.update({
    id: '/alerts/',
    path: '/alerts/',
    getParentRoute: () => SlSlAuthenticatedRoute,
  } as any)
const UsersUserIdPairSuccessRoute = UsersUserIdPairSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => UsersUserIdPairRoute,
} as any)
const UsersUserIdPairErrorRoute = UsersUserIdPairErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => UsersUserIdPairRoute,
} as any)
const SlSetPasswordInviteIdSecretRoute =
  SlSetPasswordInviteIdSecretRouteImport.update({
    id: '/sl/set-password/$inviteId/$secret',
    path: '/sl/set-password/$inviteId/$secret',
    getParentRoute: () => rootRouteImport,
  } as any)
const SlSlAuthenticatedPatientsPatientIdRoute =
  SlSlAuthenticatedPatientsPatientIdRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => SlSlAuthenticatedRoute,
  } as any)
const SlSlAuthenticatedInstructionTemplatesTemplateIdRoute =
  SlSlAuthenticatedInstructionTemplatesTemplateIdRouteImport.update({
    id: '/instruction-templates/$templateId',
    path: '/instruction-templates/$templateId',
    getParentRoute: () => SlSlAuthenticatedRoute,
  } as any)
const SlSlAuthenticatedCliniciansClinicianIdRoute =
  SlSlAuthenticatedCliniciansClinicianIdRouteImport.update({
    id: '/clinicians/$clinicianId',
    path: '/clinicians/$clinicianId',
    getParentRoute: () => SlSlAuthenticatedRoute,
  } as any)
const SlSlAuthenticatedAlertsAlertIdRoute =
  SlSlAuthenticatedAlertsAlertIdRouteImport.update({
    id: '/alerts/$alertId',
    path: '/alerts/$alertId',
    getParentRoute: () => SlSlAuthenticatedRoute,
  } as any)
const SlSlAuthenticatedPatientsPatientIdIndexRoute =
  SlSlAuthenticatedPatientsPatientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SlSlAuthenticatedPatientsPatientIdRoute,
  } as any)
const SlSlAuthenticatedInstructionTemplatesQuestionnairesQuestionnaireIdRoute =
  SlSlAuthenticatedInstructionTemplatesQuestionnairesQuestionnaireIdRouteImport.update(
    {
      id: '/instruction-templates/questionnaires/$questionnaireId',
      path: '/instruction-templates/questionnaires/$questionnaireId',
      getParentRoute: () => SlSlAuthenticatedRoute,
    } as any,
  )
const SlSlAuthenticatedPatientsPatientIdPlansPlanIdEditRoute =
  SlSlAuthenticatedPatientsPatientIdPlansPlanIdEditRouteImport.update({
    id: '/plans/$planId/edit',
    path: '/plans/$planId/edit',
    getParentRoute: () => SlSlAuthenticatedPatientsPatientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/webhooks': typeof AuthenticatedWebhooksRouteWithChildren
  '/sl': typeof SlSlAuthenticatedRouteWithChildren
  '/sl/forgot-password': typeof SlForgotPasswordRoute
  '/sl/login': typeof SlLoginRoute
  '/widget/connect': typeof WidgetConnectRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/webhooks/$endpointId': typeof AuthenticatedWebhooksEndpointIdRoute
  '/sl/dashboard': typeof SlSlAuthenticatedDashboardRoute
  '/users/$userId/pair': typeof UsersUserIdPairRouteWithChildren
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/webhooks/': typeof AuthenticatedWebhooksIndexRoute
  '/sl/alerts/$alertId': typeof SlSlAuthenticatedAlertsAlertIdRoute
  '/sl/clinicians/$clinicianId': typeof SlSlAuthenticatedCliniciansClinicianIdRoute
  '/sl/instruction-templates/$templateId': typeof SlSlAuthenticatedInstructionTemplatesTemplateIdRoute
  '/sl/patients/$patientId': typeof SlSlAuthenticatedPatientsPatientIdRouteWithChildren
  '/sl/set-password/$inviteId/$secret': typeof SlSetPasswordInviteIdSecretRoute
  '/users/$userId/pair/error': typeof UsersUserIdPairErrorRoute
  '/users/$userId/pair/success': typeof UsersUserIdPairSuccessRoute
  '/sl/alerts/': typeof SlSlAuthenticatedAlertsIndexRoute
  '/sl/clinicians/': typeof SlSlAuthenticatedCliniciansIndexRoute
  '/sl/instruction-templates/': typeof SlSlAuthenticatedInstructionTemplatesIndexRoute
  '/sl/patients/': typeof SlSlAuthenticatedPatientsIndexRoute
  '/users/$userId/pair/': typeof UsersUserIdPairIndexRoute
  '/sl/instruction-templates/questionnaires/$questionnaireId': typeof SlSlAuthenticatedInstructionTemplatesQuestionnairesQuestionnaireIdRoute
  '/sl/patients/$patientId/': typeof SlSlAuthenticatedPatientsPatientIdIndexRoute
  '/sl/patients/$patientId/plans/$planId/edit': typeof SlSlAuthenticatedPatientsPatientIdPlansPlanIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sl': typeof SlSlAuthenticatedRouteWithChildren
  '/sl/forgot-password': typeof SlForgotPasswordRoute
  '/sl/login': typeof SlLoginRoute
  '/widget/connect': typeof WidgetConnectRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/webhooks/$endpointId': typeof AuthenticatedWebhooksEndpointIdRoute
  '/sl/dashboard': typeof SlSlAuthenticatedDashboardRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/webhooks': typeof AuthenticatedWebhooksIndexRoute
  '/sl/alerts/$alertId': typeof SlSlAuthenticatedAlertsAlertIdRoute
  '/sl/clinicians/$clinicianId': typeof SlSlAuthenticatedCliniciansClinicianIdRoute
  '/sl/instruction-templates/$templateId': typeof SlSlAuthenticatedInstructionTemplatesTemplateIdRoute
  '/sl/set-password/$inviteId/$secret': typeof SlSetPasswordInviteIdSecretRoute
  '/users/$userId/pair/error': typeof UsersUserIdPairErrorRoute
  '/users/$userId/pair/success': typeof UsersUserIdPairSuccessRoute
  '/sl/alerts': typeof SlSlAuthenticatedAlertsIndexRoute
  '/sl/clinicians': typeof SlSlAuthenticatedCliniciansIndexRoute
  '/sl/instruction-templates': typeof SlSlAuthenticatedInstructionTemplatesIndexRoute
  '/sl/patients': typeof SlSlAuthenticatedPatientsIndexRoute
  '/users/$userId/pair': typeof UsersUserIdPairIndexRoute
  '/sl/instruction-templates/questionnaires/$questionnaireId': typeof SlSlAuthenticatedInstructionTemplatesQuestionnairesQuestionnaireIdRoute
  '/sl/patients/$patientId': typeof SlSlAuthenticatedPatientsPatientIdIndexRoute
  '/sl/patients/$patientId/plans/$planId/edit': typeof SlSlAuthenticatedPatientsPatientIdPlansPlanIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRouteWithChildren
  '/_authenticated/webhooks': typeof AuthenticatedWebhooksRouteWithChildren
  '/sl/_sl-authenticated': typeof SlSlAuthenticatedRouteWithChildren
  '/sl/forgot-password': typeof SlForgotPasswordRoute
  '/sl/login': typeof SlLoginRoute
  '/widget/connect': typeof WidgetConnectRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/_authenticated/webhooks/$endpointId': typeof AuthenticatedWebhooksEndpointIdRoute
  '/sl/_sl-authenticated/dashboard': typeof SlSlAuthenticatedDashboardRoute
  '/users/$userId/pair': typeof UsersUserIdPairRouteWithChildren
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/webhooks/': typeof AuthenticatedWebhooksIndexRoute
  '/sl/_sl-authenticated/alerts/$alertId': typeof SlSlAuthenticatedAlertsAlertIdRoute
  '/sl/_sl-authenticated/clinicians/$clinicianId': typeof SlSlAuthenticatedCliniciansClinicianIdRoute
  '/sl/_sl-authenticated/instruction-templates/$templateId': typeof SlSlAuthenticatedInstructionTemplatesTemplateIdRoute
  '/sl/_sl-authenticated/patients/$patientId': typeof SlSlAuthenticatedPatientsPatientIdRouteWithChildren
  '/sl/set-password/$inviteId/$secret': typeof SlSetPasswordInviteIdSecretRoute
  '/users/$userId/pair/error': typeof UsersUserIdPairErrorRoute
  '/users/$userId/pair/success': typeof UsersUserIdPairSuccessRoute
  '/sl/_sl-authenticated/alerts/': typeof SlSlAuthenticatedAlertsIndexRoute
  '/sl/_sl-authenticated/clinicians/': typeof SlSlAuthenticatedCliniciansIndexRoute
  '/sl/_sl-authenticated/instruction-templates/': typeof SlSlAuthenticatedInstructionTemplatesIndexRoute
  '/sl/_sl-authenticated/patients/': typeof SlSlAuthenticatedPatientsIndexRoute
  '/users/$userId/pair/': typeof UsersUserIdPairIndexRoute
  '/sl/_sl-authenticated/instruction-templates/questionnaires/$questionnaireId': typeof SlSlAuthenticatedInstructionTemplatesQuestionnairesQuestionnaireIdRoute
  '/sl/_sl-authenticated/patients/$patientId/': typeof SlSlAuthenticatedPatientsPatientIdIndexRoute
  '/sl/_sl-authenticated/patients/$patientId/plans/$planId/edit': typeof SlSlAuthenticatedPatientsPatientIdPlansPlanIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/settings'
    | '/users'
    | '/webhooks'
    | '/sl'
    | '/sl/forgot-password'
    | '/sl/login'
    | '/widget/connect'
    | '/users/$userId'
    | '/webhooks/$endpointId'
    | '/sl/dashboard'
    | '/users/$userId/pair'
    | '/users/'
    | '/webhooks/'
    | '/sl/alerts/$alertId'
    | '/sl/clinicians/$clinicianId'
    | '/sl/instruction-templates/$templateId'
    | '/sl/patients/$patientId'
    | '/sl/set-password/$inviteId/$secret'
    | '/users/$userId/pair/error'
    | '/users/$userId/pair/success'
    | '/sl/alerts/'
    | '/sl/clinicians/'
    | '/sl/instruction-templates/'
    | '/sl/patients/'
    | '/users/$userId/pair/'
    | '/sl/instruction-templates/questionnaires/$questionnaireId'
    | '/sl/patients/$patientId/'
    | '/sl/patients/$patientId/plans/$planId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/settings'
    | '/sl'
    | '/sl/forgot-password'
    | '/sl/login'
    | '/widget/connect'
    | '/users/$userId'
    | '/webhooks/$endpointId'
    | '/sl/dashboard'
    | '/users'
    | '/webhooks'
    | '/sl/alerts/$alertId'
    | '/sl/clinicians/$clinicianId'
    | '/sl/instruction-templates/$templateId'
    | '/sl/set-password/$inviteId/$secret'
    | '/users/$userId/pair/error'
    | '/users/$userId/pair/success'
    | '/sl/alerts'
    | '/sl/clinicians'
    | '/sl/instruction-templates'
    | '/sl/patients'
    | '/users/$userId/pair'
    | '/sl/instruction-templates/questionnaires/$questionnaireId'
    | '/sl/patients/$patientId'
    | '/sl/patients/$patientId/plans/$planId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/webhooks'
    | '/sl/_sl-authenticated'
    | '/sl/forgot-password'
    | '/sl/login'
    | '/widget/connect'
    | '/_authenticated/users/$userId'
    | '/_authenticated/webhooks/$endpointId'
    | '/sl/_sl-authenticated/dashboard'
    | '/users/$userId/pair'
    | '/_authenticated/users/'
    | '/_authenticated/webhooks/'
    | '/sl/_sl-authenticated/alerts/$alertId'
    | '/sl/_sl-authenticated/clinicians/$clinicianId'
    | '/sl/_sl-authenticated/instruction-templates/$templateId'
    | '/sl/_sl-authenticated/patients/$patientId'
    | '/sl/set-password/$inviteId/$secret'
    | '/users/$userId/pair/error'
    | '/users/$userId/pair/success'
    | '/sl/_sl-authenticated/alerts/'
    | '/sl/_sl-authenticated/clinicians/'
    | '/sl/_sl-authenticated/instruction-templates/'
    | '/sl/_sl-authenticated/patients/'
    | '/users/$userId/pair/'
    | '/sl/_sl-authenticated/instruction-templates/questionnaires/$questionnaireId'
    | '/sl/_sl-authenticated/patients/$patientId/'
    | '/sl/_sl-authenticated/patients/$patientId/plans/$planId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SlSlAuthenticatedRoute: typeof SlSlAuthenticatedRouteWithChildren
  SlForgotPasswordRoute: typeof SlForgotPasswordRoute
  SlLoginRoute: typeof SlLoginRoute
  WidgetConnectRoute: typeof WidgetConnectRoute
  UsersUserIdPairRoute: typeof UsersUserIdPairRouteWithChildren
  SlSetPasswordInviteIdSecretRoute: typeof SlSetPasswordInviteIdSecretRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/connect': {
      id: '/widget/connect'
      path: '/widget/connect'
      fullPath: '/widget/connect'
      preLoaderRoute: typeof WidgetConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sl/login': {
      id: '/sl/login'
      path: '/sl/login'
      fullPath: '/sl/login'
      preLoaderRoute: typeof SlLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sl/forgot-password': {
      id: '/sl/forgot-password'
      path: '/sl/forgot-password'
      fullPath: '/sl/forgot-password'
      preLoaderRoute: typeof SlForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sl/_sl-authenticated': {
      id: '/sl/_sl-authenticated'
      path: '/sl'
      fullPath: '/sl'
      preLoaderRoute: typeof SlSlAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/webhooks': {
      id: '/_authenticated/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AuthenticatedWebhooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/webhooks/': {
      id: '/_authenticated/webhooks/'
      path: '/'
      fullPath: '/webhooks/'
      preLoaderRoute: typeof AuthenticatedWebhooksIndexRouteImport
      parentRoute: typeof AuthenticatedWebhooksRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/users/$userId/pair': {
      id: '/users/$userId/pair'
      path: '/users/$userId/pair'
      fullPath: '/users/$userId/pair'
      preLoaderRoute: typeof UsersUserIdPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sl/_sl-authenticated/dashboard': {
      id: '/sl/_sl-authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/sl/dashboard'
      preLoaderRoute: typeof SlSlAuthenticatedDashboardRouteImport
      parentRoute: typeof SlSlAuthenticatedRoute
    }
    '/_authenticated/webhooks/$endpointId': {
      id: '/_authenticated/webhooks/$endpointId'
      path: '/$endpointId'
      fullPath: '/webhooks/$endpointId'
      preLoaderRoute: typeof AuthenticatedWebhooksEndpointIdRouteImport
      parentRoute: typeof AuthenticatedWebhooksRoute
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/users/$userId/pair/': {
      id: '/users/$userId/pair/'
      path: '/'
      fullPath: '/users/$userId/pair/'
      preLoaderRoute: typeof UsersUserIdPairIndexRouteImport
      parentRoute: typeof UsersUserIdPairRoute
    }
    '/sl/_sl-authenticated/patients/': {
      id: '/sl/_sl-authenticated/patients/'
      path: '/patients'
      fullPath: '/sl/patients/'
      preLoaderRoute: typeof SlSlAuthenticatedPatientsIndexRouteImport
      parentRoute: typeof SlSlAuthenticatedRoute
    }
    '/sl/_sl-authenticated/instruction-templates/': {
      id: '/sl/_sl-authenticated/instruction-templates/'
      path: '/instruction-templates'
      fullPath: '/sl/instruction-templates/'
      preLoaderRoute: typeof SlSlAuthenticatedInstructionTemplatesIndexRouteImport
      parentRoute: typeof SlSlAuthenticatedRoute
    }
    '/sl/_sl-authenticated/clinicians/': {
      id: '/sl/_sl-authenticated/clinicians/'
      path: '/clinicians'
      fullPath: '/sl/clinicians/'
      preLoaderRoute: typeof SlSlAuthenticatedCliniciansIndexRouteImport
      parentRoute: typeof SlSlAuthenticatedRoute
    }
    '/sl/_sl-authenticated/alerts/': {
      id: '/sl/_sl-authenticated/alerts/'
      path: '/alerts'
      fullPath: '/sl/alerts/'
      preLoaderRoute: typeof SlSlAuthenticatedAlertsIndexRouteImport
      parentRoute: typeof SlSlAuthenticatedRoute
    }
    '/users/$userId/pair/success': {
      id: '/users/$userId/pair/success'
      path: '/success'
      fullPath: '/users/$userId/pair/success'
      preLoaderRoute: typeof UsersUserIdPairSuccessRouteImport
      parentRoute: typeof UsersUserIdPairRoute
    }
    '/users/$userId/pair/error': {
      id: '/users/$userId/pair/error'
      path: '/error'
      fullPath: '/users/$userId/pair/error'
      preLoaderRoute: typeof UsersUserIdPairErrorRouteImport
      parentRoute: typeof UsersUserIdPairRoute
    }
    '/sl/set-password/$inviteId/$secret': {
      id: '/sl/set-password/$inviteId/$secret'
      path: '/sl/set-password/$inviteId/$secret'
      fullPath: '/sl/set-password/$inviteId/$secret'
      preLoaderRoute: typeof SlSetPasswordInviteIdSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sl/_sl-authenticated/patients/$patientId': {
      id: '/sl/_sl-authenticated/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/sl/patients/$patientId'
      preLoaderRoute: typeof SlSlAuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof SlSlAuthenticatedRoute
    }
    '/sl/_sl-authenticated/instruction-templates/$templateId': {
      id: '/sl/_sl-authenticated/instruction-templates/$templateId'
      path: '/instruction-templates/$templateId'
      fullPath: '/sl/instruction-templates/$templateId'
      preLoaderRoute: typeof SlSlAuthenticatedInstructionTemplatesTemplateIdRouteImport
      parentRoute: typeof SlSlAuthenticatedRoute
    }
    '/sl/_sl-authenticated/clinicians/$clinicianId': {
      id: '/sl/_sl-authenticated/clinicians/$clinicianId'
      path: '/clinicians/$clinicianId'
      fullPath: '/sl/clinicians/$clinicianId'
      preLoaderRoute: typeof SlSlAuthenticatedCliniciansClinicianIdRouteImport
      parentRoute: typeof SlSlAuthenticatedRoute
    }
    '/sl/_sl-authenticated/alerts/$alertId': {
      id: '/sl/_sl-authenticated/alerts/$alertId'
      path: '/alerts/$alertId'
      fullPath: '/sl/alerts/$alertId'
      preLoaderRoute: typeof SlSlAuthenticatedAlertsAlertIdRouteImport
      parentRoute: typeof SlSlAuthenticatedRoute
    }
    '/sl/_sl-authenticated/patients/$patientId/': {
      id: '/sl/_sl-authenticated/patients/$patientId/'
      path: '/'
      fullPath: '/sl/patients/$patientId/'
      preLoaderRoute: typeof SlSlAuthenticatedPatientsPatientIdIndexRouteImport
      parentRoute: typeof SlSlAuthenticatedPatientsPatientIdRoute
    }
    '/sl/_sl-authenticated/instruction-templates/questionnaires/$questionnaireId': {
      id: '/sl/_sl-authenticated/instruction-templates/questionnaires/$questionnaireId'
      path: '/instruction-templates/questionnaires/$questionnaireId'
      fullPath: '/sl/instruction-templates/questionnaires/$questionnaireId'
      preLoaderRoute: typeof SlSlAuthenticatedInstructionTemplatesQuestionnairesQuestionnaireIdRouteImport
      parentRoute: typeof SlSlAuthenticatedRoute
    }
    '/sl/_sl-authenticated/patients/$patientId/plans/$planId/edit': {
      id: '/sl/_sl-authenticated/patients/$patientId/plans/$planId/edit'
      path: '/plans/$planId/edit'
      fullPath: '/sl/patients/$patientId/plans/$planId/edit'
      preLoaderRoute: typeof SlSlAuthenticatedPatientsPatientIdPlansPlanIdEditRouteImport
      parentRoute: typeof SlSlAuthenticatedPatientsPatientIdRoute
    }
  }
}

interface AuthenticatedUsersRouteChildren {
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedUsersRouteChildren: AuthenticatedUsersRouteChildren = {
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedUsersRouteWithChildren =
  AuthenticatedUsersRoute._addFileChildren(AuthenticatedUsersRouteChildren)

interface AuthenticatedWebhooksRouteChildren {
  AuthenticatedWebhooksEndpointIdRoute: typeof AuthenticatedWebhooksEndpointIdRoute
  AuthenticatedWebhooksIndexRoute: typeof AuthenticatedWebhooksIndexRoute
}

const AuthenticatedWebhooksRouteChildren: AuthenticatedWebhooksRouteChildren = {
  AuthenticatedWebhooksEndpointIdRoute: AuthenticatedWebhooksEndpointIdRoute,
  AuthenticatedWebhooksIndexRoute: AuthenticatedWebhooksIndexRoute,
}

const AuthenticatedWebhooksRouteWithChildren =
  AuthenticatedWebhooksRoute._addFileChildren(
    AuthenticatedWebhooksRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRouteWithChildren
  AuthenticatedWebhooksRoute: typeof AuthenticatedWebhooksRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRouteWithChildren,
  AuthenticatedWebhooksRoute: AuthenticatedWebhooksRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SlSlAuthenticatedPatientsPatientIdRouteChildren {
  SlSlAuthenticatedPatientsPatientIdIndexRoute: typeof SlSlAuthenticatedPatientsPatientIdIndexRoute
  SlSlAuthenticatedPatientsPatientIdPlansPlanIdEditRoute: typeof SlSlAuthenticatedPatientsPatientIdPlansPlanIdEditRoute
}

const SlSlAuthenticatedPatientsPatientIdRouteChildren: SlSlAuthenticatedPatientsPatientIdRouteChildren =
  {
    SlSlAuthenticatedPatientsPatientIdIndexRoute:
      SlSlAuthenticatedPatientsPatientIdIndexRoute,
    SlSlAuthenticatedPatientsPatientIdPlansPlanIdEditRoute:
      SlSlAuthenticatedPatientsPatientIdPlansPlanIdEditRoute,
  }

const SlSlAuthenticatedPatientsPatientIdRouteWithChildren =
  SlSlAuthenticatedPatientsPatientIdRoute._addFileChildren(
    SlSlAuthenticatedPatientsPatientIdRouteChildren,
  )

interface SlSlAuthenticatedRouteChildren {
  SlSlAuthenticatedDashboardRoute: typeof SlSlAuthenticatedDashboardRoute
  SlSlAuthenticatedAlertsAlertIdRoute: typeof SlSlAuthenticatedAlertsAlertIdRoute
  SlSlAuthenticatedCliniciansClinicianIdRoute: typeof SlSlAuthenticatedCliniciansClinicianIdRoute
  SlSlAuthenticatedInstructionTemplatesTemplateIdRoute: typeof SlSlAuthenticatedInstructionTemplatesTemplateIdRoute
  SlSlAuthenticatedPatientsPatientIdRoute: typeof SlSlAuthenticatedPatientsPatientIdRouteWithChildren
  SlSlAuthenticatedAlertsIndexRoute: typeof SlSlAuthenticatedAlertsIndexRoute
  SlSlAuthenticatedCliniciansIndexRoute: typeof SlSlAuthenticatedCliniciansIndexRoute
  SlSlAuthenticatedInstructionTemplatesIndexRoute: typeof SlSlAuthenticatedInstructionTemplatesIndexRoute
  SlSlAuthenticatedPatientsIndexRoute: typeof SlSlAuthenticatedPatientsIndexRoute
  SlSlAuthenticatedInstructionTemplatesQuestionnairesQuestionnaireIdRoute: typeof SlSlAuthenticatedInstructionTemplatesQuestionnairesQuestionnaireIdRoute
}

const SlSlAuthenticatedRouteChildren: SlSlAuthenticatedRouteChildren = {
  SlSlAuthenticatedDashboardRoute: SlSlAuthenticatedDashboardRoute,
  SlSlAuthenticatedAlertsAlertIdRoute: SlSlAuthenticatedAlertsAlertIdRoute,
  SlSlAuthenticatedCliniciansClinicianIdRoute:
    SlSlAuthenticatedCliniciansClinicianIdRoute,
  SlSlAuthenticatedInstructionTemplatesTemplateIdRoute:
    SlSlAuthenticatedInstructionTemplatesTemplateIdRoute,
  SlSlAuthenticatedPatientsPatientIdRoute:
    SlSlAuthenticatedPatientsPatientIdRouteWithChildren,
  SlSlAuthenticatedAlertsIndexRoute: SlSlAuthenticatedAlertsIndexRoute,
  SlSlAuthenticatedCliniciansIndexRoute: SlSlAuthenticatedCliniciansIndexRoute,
  SlSlAuthenticatedInstructionTemplatesIndexRoute:
    SlSlAuthenticatedInstructionTemplatesIndexRoute,
  SlSlAuthenticatedPatientsIndexRoute: SlSlAuthenticatedPatientsIndexRoute,
  SlSlAuthenticatedInstructionTemplatesQuestionnairesQuestionnaireIdRoute:
    SlSlAuthenticatedInstructionTemplatesQuestionnairesQuestionnaireIdRoute,
}

const SlSlAuthenticatedRouteWithChildren =
  SlSlAuthenticatedRoute._addFileChildren(SlSlAuthenticatedRouteChildren)

interface UsersUserIdPairRouteChildren {
  UsersUserIdPairErrorRoute: typeof UsersUserIdPairErrorRoute
  UsersUserIdPairSuccessRoute: typeof UsersUserIdPairSuccessRoute
  UsersUserIdPairIndexRoute: typeof UsersUserIdPairIndexRoute
}

const UsersUserIdPairRouteChildren: UsersUserIdPairRouteChildren = {
  UsersUserIdPairErrorRoute: UsersUserIdPairErrorRoute,
  UsersUserIdPairSuccessRoute: UsersUserIdPairSuccessRoute,
  UsersUserIdPairIndexRoute: UsersUserIdPairIndexRoute,
}

const UsersUserIdPairRouteWithChildren = UsersUserIdPairRoute._addFileChildren(
  UsersUserIdPairRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SlSlAuthenticatedRoute: SlSlAuthenticatedRouteWithChildren,
  SlForgotPasswordRoute: SlForgotPasswordRoute,
  SlLoginRoute: SlLoginRoute,
  WidgetConnectRoute: WidgetConnectRoute,
  UsersUserIdPairRoute: UsersUserIdPairRouteWithChildren,
  SlSetPasswordInviteIdSecretRoute: SlSetPasswordInviteIdSecretRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
