"""Add Sense Loop extension tables

Revision ID: 957da397ab9e
Revises: a7b8c9d0e1f2

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '957da397ab9e'
down_revision: Union[str, None] = 'a7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sl_organization',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sl_practitioner',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('npi_number', sa.String(length=50), nullable=True),
    sa.Column('credentials', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sl_alert_protocol',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rules_hash', sa.String(length=100), nullable=True),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['sl_practitioner.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['sl_organization.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['sl_alert_protocol.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sl_alert_protocol_organization_id'), 'sl_alert_protocol', ['organization_id'], unique=False)
    op.create_table('sl_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('resource_name', sa.String(length=255), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('http_method', sa.String(length=50), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('outcome_reason', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('phi_fields_accessed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['sl_organization.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sl_audit_log_organization_id'), 'sl_audit_log', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sl_audit_log_request_id'), 'sl_audit_log', ['request_id'], unique=False)
    op.create_table('sl_practitioner_invite',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('invite_secret', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invited_by_id', sa.UUID(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_send_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['sl_practitioner.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['sl_organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sl_practitioner_invite_organization_id'), 'sl_practitioner_invite', ['organization_id'], unique=False)
    op.create_table('sl_questionnaire',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('questionnaire_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('allow_skip', sa.Boolean(), nullable=False),
    sa.Column('require_completion', sa.Boolean(), nullable=False),
    sa.Column('has_scoring', sa.Boolean(), nullable=False),
    sa.Column('scoring_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['sl_organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sl_questionnaire_organization_id'), 'sl_questionnaire', ['organization_id'], unique=False)
    op.create_table('sl_role_definition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('can_manage_patients', sa.Boolean(), nullable=False),
    sa.Column('can_manage_alerts', sa.Boolean(), nullable=False),
    sa.Column('can_resolve_alerts', sa.Boolean(), nullable=False),
    sa.Column('can_acknowledge_alerts', sa.Boolean(), nullable=False),
    sa.Column('can_manage_care_plans', sa.Boolean(), nullable=False),
    sa.Column('can_manage_clinicians', sa.Boolean(), nullable=False),
    sa.Column('can_manage_org_settings', sa.Boolean(), nullable=False),
    sa.Column('can_view_audit_logs', sa.Boolean(), nullable=False),
    sa.Column('can_manage_alert_protocols', sa.Boolean(), nullable=False),
    sa.Column('can_export_data', sa.Boolean(), nullable=False),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['sl_organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_role_org_code')
    )
    op.create_index(op.f('ix_sl_role_definition_organization_id'), 'sl_role_definition', ['organization_id'], unique=False)
    op.create_table('sl_alert_protocol_rule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('protocol_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vital_type', sa.String(length=50), nullable=False),
    sa.Column('high_critical', sa.Float(), nullable=True),
    sa.Column('high_warning', sa.Float(), nullable=True),
    sa.Column('low_warning', sa.Float(), nullable=True),
    sa.Column('low_critical', sa.Float(), nullable=True),
    sa.Column('context', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('alert_severity', sa.String(length=50), nullable=False),
    sa.Column('sustained_seconds', sa.Integer(), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('notify_patient', sa.Boolean(), nullable=False),
    sa.Column('notify_care_team', sa.Boolean(), nullable=False),
    sa.Column('escalation_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['sl_alert_protocol.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sl_alert_protocol_rule_protocol_id'), 'sl_alert_protocol_rule', ['protocol_id'], unique=False)
    op.create_table('sl_alert_risk_window',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('protocol_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_day', sa.Integer(), nullable=False),
    sa.Column('end_day', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('threshold_adjustments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['sl_alert_protocol.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sl_alert_risk_window_protocol_id'), 'sl_alert_risk_window', ['protocol_id'], unique=False)
    op.create_table('sl_patient',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ow_user_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('mrn', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('activation_code', sa.String(length=50), nullable=True),
    sa.Column('activation_code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrollment_status', sa.String(length=50), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discharged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('primary_diagnosis', sa.String(length=255), nullable=True),
    sa.Column('surgery_date', sa.Date(), nullable=True),
    sa.Column('discharge_date', sa.Date(), nullable=True),
    sa.Column('monitoring_start_date', sa.Date(), nullable=True),
    sa.Column('monitoring_end_date', sa.Date(), nullable=True),
    sa.Column('alert_protocol_id', sa.UUID(), nullable=True),
    sa.Column('custom_thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_protocol_id'], ['sl_alert_protocol.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['sl_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ow_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sl_patient_activation_code'), 'sl_patient', ['activation_code'], unique=False)
    op.create_index(op.f('ix_sl_patient_mrn'), 'sl_patient', ['mrn'], unique=False)
    op.create_index(op.f('ix_sl_patient_organization_id'), 'sl_patient', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sl_patient_ow_user_id'), 'sl_patient', ['ow_user_id'], unique=True)
    op.create_index(op.f('ix_sl_patient_surgery_date'), 'sl_patient', ['surgery_date'], unique=False)
    op.create_table('sl_practitioner_role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practitioner_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role_definition_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['sl_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practitioner_id'], ['sl_practitioner.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_definition_id'], ['sl_role_definition.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practitioner_id', 'organization_id', name='uq_practitioner_org')
    )
    op.create_index(op.f('ix_sl_practitioner_role_organization_id'), 'sl_practitioner_role', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sl_practitioner_role_practitioner_id'), 'sl_practitioner_role', ['practitioner_id'], unique=False)
    op.create_index(op.f('ix_sl_practitioner_role_role_definition_id'), 'sl_practitioner_role', ['role_definition_id'], unique=False)
    op.create_table('sl_questionnaire_question',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('questionnaire_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('validation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score_weight', sa.Float(), nullable=True),
    sa.Column('alert_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['sl_questionnaire.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sl_questionnaire_question_questionnaire_id'), 'sl_questionnaire_question', ['questionnaire_id'], unique=False)
    op.create_table('sl_alert',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_id', sa.UUID(), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolution_type', sa.String(length=50), nullable=True),
    sa.Column('protocol_id', sa.UUID(), nullable=True),
    sa.Column('protocol_version', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('risk_window_id', sa.UUID(), nullable=True),
    sa.Column('days_post_surgery', sa.Integer(), nullable=True),
    sa.Column('patient_context', sa.String(length=50), nullable=True),
    sa.Column('vital_type', sa.String(length=50), nullable=True),
    sa.Column('observed_value', sa.Float(), nullable=True),
    sa.Column('threshold_breached', sa.String(length=50), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['sl_practitioner.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['sl_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['sl_patient.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['protocol_id'], ['sl_alert_protocol.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['sl_practitioner.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['risk_window_id'], ['sl_alert_risk_window.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['sl_alert_protocol_rule.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sl_alert_organization_id'), 'sl_alert', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sl_alert_patient_id'), 'sl_alert', ['patient_id'], unique=False)
    op.create_index(op.f('ix_sl_alert_status'), 'sl_alert', ['status'], unique=False)
    op.create_index(op.f('ix_sl_alert_triggered_at'), 'sl_alert', ['triggered_at'], unique=False)
    op.create_table('sl_care_plan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('questionnaire_id', sa.UUID(), nullable=True),
    sa.Column('questionnaire_schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['sl_practitioner.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['sl_patient.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['sl_questionnaire.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['sl_practitioner.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sl_care_plan_patient_id'), 'sl_care_plan', ['patient_id'], unique=False)
    op.create_index(op.f('ix_sl_care_plan_status'), 'sl_care_plan', ['status'], unique=False)
    op.create_table('sl_patient_summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('latest_heart_rate', sa.Float(), nullable=True),
    sa.Column('latest_heart_rate_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_spo2', sa.Float(), nullable=True),
    sa.Column('latest_spo2_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_temperature', sa.Float(), nullable=True),
    sa.Column('latest_temperature_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_blood_pressure_systolic', sa.Float(), nullable=True),
    sa.Column('latest_blood_pressure_diastolic', sa.Float(), nullable=True),
    sa.Column('latest_blood_pressure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_hrv', sa.Float(), nullable=True),
    sa.Column('latest_hrv_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_respiratory_rate', sa.Float(), nullable=True),
    sa.Column('latest_respiratory_rate_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('today_steps', sa.Integer(), nullable=True),
    sa.Column('today_active_calories', sa.Float(), nullable=True),
    sa.Column('today_distance_meters', sa.Float(), nullable=True),
    sa.Column('today_active_minutes', sa.Integer(), nullable=True),
    sa.Column('last_sleep_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('last_sleep_score', sa.Float(), nullable=True),
    sa.Column('last_sleep_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_recovery_score', sa.Float(), nullable=True),
    sa.Column('latest_recovery_score_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_readiness_score', sa.Float(), nullable=True),
    sa.Column('latest_readiness_score_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heart_rate_trend', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spo2_trend', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sleep_trend', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('activity_trend', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active_alerts_count', sa.Integer(), nullable=False),
    sa.Column('active_critical_alerts_count', sa.Integer(), nullable=False),
    sa.Column('last_alert_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pending_questionnaires_count', sa.Integer(), nullable=False),
    sa.Column('last_questionnaire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_data_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('overall_status', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['sl_patient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sl_patient_summary_patient_id'), 'sl_patient_summary', ['patient_id'], unique=True)
    op.create_table('sl_questionnaire_response',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('questionnaire_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('score_interpretation', sa.String(length=50), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['sl_patient.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['sl_questionnaire.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['sl_practitioner.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sl_questionnaire_response_patient_id'), 'sl_questionnaire_response', ['patient_id'], unique=False)
    op.create_index(op.f('ix_sl_questionnaire_response_questionnaire_id'), 'sl_questionnaire_response', ['questionnaire_id'], unique=False)
    op.create_index(op.f('ix_sl_questionnaire_response_status'), 'sl_questionnaire_response', ['status'], unique=False)
    op.create_table('sl_questionnaire_answer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('response_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('value_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['sl_questionnaire_question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['sl_questionnaire_response.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sl_questionnaire_answer_question_id'), 'sl_questionnaire_answer', ['question_id'], unique=False)
    op.create_index(op.f('ix_sl_questionnaire_answer_response_id'), 'sl_questionnaire_answer', ['response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sl_questionnaire_answer_response_id'), table_name='sl_questionnaire_answer')
    op.drop_index(op.f('ix_sl_questionnaire_answer_question_id'), table_name='sl_questionnaire_answer')
    op.drop_table('sl_questionnaire_answer')
    op.drop_index(op.f('ix_sl_questionnaire_response_status'), table_name='sl_questionnaire_response')
    op.drop_index(op.f('ix_sl_questionnaire_response_questionnaire_id'), table_name='sl_questionnaire_response')
    op.drop_index(op.f('ix_sl_questionnaire_response_patient_id'), table_name='sl_questionnaire_response')
    op.drop_table('sl_questionnaire_response')
    op.drop_index(op.f('ix_sl_patient_summary_patient_id'), table_name='sl_patient_summary')
    op.drop_table('sl_patient_summary')
    op.drop_index(op.f('ix_sl_care_plan_status'), table_name='sl_care_plan')
    op.drop_index(op.f('ix_sl_care_plan_patient_id'), table_name='sl_care_plan')
    op.drop_table('sl_care_plan')
    op.drop_index(op.f('ix_sl_alert_triggered_at'), table_name='sl_alert')
    op.drop_index(op.f('ix_sl_alert_status'), table_name='sl_alert')
    op.drop_index(op.f('ix_sl_alert_patient_id'), table_name='sl_alert')
    op.drop_index(op.f('ix_sl_alert_organization_id'), table_name='sl_alert')
    op.drop_table('sl_alert')
    op.drop_index(op.f('ix_sl_questionnaire_question_questionnaire_id'), table_name='sl_questionnaire_question')
    op.drop_table('sl_questionnaire_question')
    op.drop_index(op.f('ix_sl_practitioner_role_role_definition_id'), table_name='sl_practitioner_role')
    op.drop_index(op.f('ix_sl_practitioner_role_practitioner_id'), table_name='sl_practitioner_role')
    op.drop_index(op.f('ix_sl_practitioner_role_organization_id'), table_name='sl_practitioner_role')
    op.drop_table('sl_practitioner_role')
    op.drop_index(op.f('ix_sl_patient_surgery_date'), table_name='sl_patient')
    op.drop_index(op.f('ix_sl_patient_ow_user_id'), table_name='sl_patient')
    op.drop_index(op.f('ix_sl_patient_organization_id'), table_name='sl_patient')
    op.drop_index(op.f('ix_sl_patient_mrn'), table_name='sl_patient')
    op.drop_index(op.f('ix_sl_patient_activation_code'), table_name='sl_patient')
    op.drop_table('sl_patient')
    op.drop_index(op.f('ix_sl_alert_risk_window_protocol_id'), table_name='sl_alert_risk_window')
    op.drop_table('sl_alert_risk_window')
    op.drop_index(op.f('ix_sl_alert_protocol_rule_protocol_id'), table_name='sl_alert_protocol_rule')
    op.drop_table('sl_alert_protocol_rule')
    op.drop_index(op.f('ix_sl_role_definition_organization_id'), table_name='sl_role_definition')
    op.drop_table('sl_role_definition')
    op.drop_index(op.f('ix_sl_questionnaire_organization_id'), table_name='sl_questionnaire')
    op.drop_table('sl_questionnaire')
    op.drop_index(op.f('ix_sl_practitioner_invite_organization_id'), table_name='sl_practitioner_invite')
    op.drop_table('sl_practitioner_invite')
    op.drop_index(op.f('ix_sl_audit_log_request_id'), table_name='sl_audit_log')
    op.drop_index(op.f('ix_sl_audit_log_organization_id'), table_name='sl_audit_log')
    op.drop_table('sl_audit_log')
    op.drop_index(op.f('ix_sl_alert_protocol_organization_id'), table_name='sl_alert_protocol')
    op.drop_table('sl_alert_protocol')
    op.drop_table('sl_practitioner')
    op.drop_table('sl_organization')
    # ### end Alembic commands ###
