"""add_surgery_type_code_to_patient

Revision ID: c905ed13b9aa
Revises: dc73cceb7f66

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c905ed13b9aa'
down_revision: Union[str, None] = 'dc73cceb7f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sl_patient', sa.Column('surgery_type_code', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sl_patient', 'surgery_type_code')
    # ### end Alembic commands ###
